version: 2
jobs:
  build:
    working_directory: ~/TTR
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run test and store coverage
          command: yarn test && codeclimate-test-reporter < /var/www/html/tag-tes-recettes_web/coverage/lcov-report/lcov.info
      - store_artifacts:
          path: coverage

