version: 2
jobs:
  build:
    working_directory: ~/TTR
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test
