version: 2
jobs:
  build:
    working_directory: ~/TTR
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run test
          command: yarn test
      - store_artifacts:
          path: coverage
      - run:
          name: Send coverage to codebeat
          command: CODECLIMATE_API_HOST=${CODECLIMATE_API_HOST} CODECLIMATE_REPO_TOKEN=${CODECLIMATE_REPO_TOKEN} ./node_modules/.bin/codeclimate-test-reporter < /home/circleci/TTR/coverage/lcov.info

