version: 2
jobs:
  build:
    working_directory: ~/TTR
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run test and store coverage
          command: yarn test && CODECLIMATE_API_HOST=$CODECLIMATE_API_HOST \
            CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN \ ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
      - store_artifacts:
          path: coverage

