version: 2
jobs:
  build:
    working_directory: ~/TTR
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: yarn test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_artifacts:
          path: coverage

